### Health
GET http://localhost:8080/health

### Tokenize
POST http://localhost:8080/tokenize

who's on first?

# curl -d"Who's on first?" http://localhost:8080/tokenize
# return json {"tokens": ["who", "on", "first"]}

### Stem
GET http://localhost:8080/stem/working